name: Jira Find issue key
description: Find an issue inside event
branding:
  icon: 'book-open'
  color: 'blue'
inputs:
  string:
    description: Provide a string to extract issue key from
    required: false
  from:
    description: Find from predefined place (should be either 'branch', or 'commits')
    required: false
    default: commits
outputs:
  issues:
    description: Key of the found issue
  markdown:
    description: Generated markdown
  has_issues:
    description: Whether there are any issues found
runs:
  using: 'node16'
  main: './dist/index.js'
